// Fill these with your Supabase project values:
export const SUPABASE_URL = 'https://sdakprxhtawytdygrntt.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkYWtwcnhodGF3eXRkeWdybnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjk2NTMsImV4cCI6MjA3MDc0NTY1M30.EMa40E9bSPJIhPVwK3gau8ce5s_GpJjkRu6ZsBoh_f4';